// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3 = "CgkIgqud_t8LEAIQAg"; // <GPGSID>
        public const string achievement_4 = "CgkIgqud_t8LEAIQAw"; // <GPGSID>
        public const string achievement_5 = "CgkIgqud_t8LEAIQBA"; // <GPGSID>
        public const string achievement_6 = "CgkIgqud_t8LEAIQBQ"; // <GPGSID>
        public const string achievement_7 = "CgkIgqud_t8LEAIQBg"; // <GPGSID>
        public const string achievement_8 = "CgkIgqud_t8LEAIQBw"; // <GPGSID>
        public const string achievement_9 = "CgkIgqud_t8LEAIQCA"; // <GPGSID>
        public const string achievement_10 = "CgkIgqud_t8LEAIQCQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIgqud_t8LEAIQCg"; // <GPGSID>
        public const string achievement_1 = "CgkIgqud_t8LEAIQAA"; // <GPGSID>
        public const string achievement_2 = "CgkIgqud_t8LEAIQAQ"; // <GPGSID>

}

